/* Database schema to keep the structure of entire database. */

-------------------------------------------
-- 1st task
CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  escape_attempts INT NOT NULL,
  neutered BOOLEAN NOT NULL,
  weight_kg DECIMAL NOT NULL
);

-------------------------------------------
-- 2nd task
ALTER TABLE animals
ADD species VARCHAR(100);

-------------------------------------------
-- 3rd task
CREATE TABLE owners (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  age VARCHAR(3)
);
CREATE TABLE species (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);


ALTER TABLE animals ADD PRIMARY KEY (id);
ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD species_id INT;
ALTER TABLE animals
ADD CONSTRAINT fk_species_id
FOREIGN KEY (species_id)
REFERENCES species(id)
ON DELETE CASCADE;

ALTER TABLE animals ADD owner_id INT;
ALTER TABLE animals
ADD CONSTRAINT fk_owner_id
FOREIGN KEY (owner_id)
REFERENCES owners(id)
ON DELETE CASCADE;

-------------------------------------------
-- 4th task
CREATE TABLE vets (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR ( 100 ) UNIQUE NOT NULL,
	age INT,
	date_of_graduation DATE
);

CREATE TABLE specializations (
	vet_id INT,
  species_id INT,
   PRIMARY KEY (vet_id, species_id),
  CONSTRAINT fk_vet_id
    FOREIGN KEY (vet_id)
      REFERENCES vets(id)
        ON DELETE CASCADE,
  CONSTRAINT fk_species_id
      FOREIGN KEY (species_id)
        REFERENCES species(id)
          ON DELETE CASCADE
);

CREATE TABLE visits (
	vet_id INT,
	animal_id INT,
	date_of_visit DATE,
  PRIMARY KEY (vet_id, animal_id, date_of_visit),
  CONSTRAINT fk_vet_id
    FOREIGN KEY (vet_id)
      REFERENCES vets(id)
        ON DELETE CASCADE,
  CONSTRAINT fk_animal_id
    FOREIGN KEY (animal_id)
      REFERENCES animals(id)
        ON DELETE CASCADE
);