/* Database schema to keep the structure of entire database. */

-- 1st task
CREATE TABLE animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  escape_attempts INT NOT NULL,
  neutered BOOLEAN NOT NULL,
  weight_kg DECIMAL NOT NULL
);

-- 2nd task
ALTER TABLE animals
ADD species VARCHAR(100);